name: build

on:
  pull_request:
    paths-ignore:
      - ".github/scripts/**"
      - "demo/**"
      - "docker/**"
      - "tools/**"
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PIP_PRE: 1

jobs:
  build_cpu_model_convert:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    strategy:
      matrix:
        torch: [2.5.1]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '${{ matrix.python-version }}'
      - name: Install PyTorch
        run: |
          uv pip install torch==${{ matrix.torch }} torchvision
      - name: Install unit tests dependencies
        run: |
          uv pip install onedl-mim
          mim install onedl-mmcv --only-binary=onedl-mmcv
          uv export --only-group codebases > codebases.txt && mim install -r codebases.txt
          uv pip install -r pyproject.toml --group tests --group build --extra backends
      # - name: Install mmyolo
      #   run: |
      #     git clone -b dev --depth 1 https://github.com/open-mmlab/mmyolo.git /home/runner/work/mmyolo
      #     python -m pip install -v -e /home/runner/work/mmyolo
      # - name: Install mmpose
      #   run: |
      #     git clone --depth 1 https://github.com/open-mmlab/mmpose.git /home/runner/work/mmpose
      #     python -m pip install -v -e /home/runner/work/mmpose
      - name: Build and install
        run: |
          rm -rf .eggs && uv pip install -e .
          python tools/check_env.py
      - name: Run python unittests and generate coverage report
        run: |
          coverage run --branch --source mmdeploy -m pytest -rsE tests
          coverage xml
          coverage report -m
      # - name: Run mmyolo deploy unittests
      #   id: badge_status
      #   run: |
      #     python -m pip install xdoctest
      #     cd /home/runner/work/mmyolo
      #     pytest tests/test_deploy
      - name: create badge
        if: always()
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: build_cpu_model_convert
          LABEL: 'build'
          # STATUS: ${{ steps.badge_status.conclusion == 'success' && 'passing' || 'failing' }}
          STATUS: 'unknown'
          # COLOR: ${{ steps.badge_status.conclusion == 'success' && 'green' || 'red' }}
          COLOR: 'yellow'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_cpu_sdk:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: update
        run: sudo apt update
      - name: gcc-multilib
        run: |
          sudo apt install -y gcc-multilib g++-multilib wget libprotobuf-dev protobuf-compiler
          sudo apt update
          sudo apt install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libxrender-dev libc++1 libc++abi1
          sudo apt install -y libopencv-dev lcov wget cmake
      - name: Build and run SDK unit test without backend
        id: badge_status
        run: |
          mkdir -p build && pushd build
          cmake .. -DCMAKE_CXX_COMPILER=g++  -DMMDEPLOY_CODEBASES=all    -DMMDEPLOY_BUILD_SDK=ON     -DMMDEPLOY_BUILD_SDK_PYTHON_API=OFF     -DMMDEPLOY_TARGET_DEVICES=cpu   -DMMDEPLOY_COVERAGE=ON  -DMMDEPLOY_BUILD_TEST=ON
          make -j2
          mkdir -p mmdeploy_test_resources/transform
          cp ../tests/data/tiger.jpeg mmdeploy_test_resources/transform/
          cd build/ && ctest --output-on-failure
          lcov --capture --directory . --output-file coverage.info
          ls -lah coverage.info
          cp coverage.info ../
      - name: create badge
        if: always()
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: build_cpu_sdk
          LABEL: 'build'
          STATUS: ${{ steps.badge_status.conclusion == 'success' && 'passing' || 'failing' }}
          COLOR: ${{ steps.badge_status.conclusion == 'success' && 'green' || 'red' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_cuda:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    strategy:
      matrix:
        image: ['nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04', 'nvidia/cuda:12.9.1-cudnn-devel-ubuntu22.04']
    permissions:
      contents: write
    container:
      image: ${{ matrix.image }}
    env:
      FORCE_CUDA: 1
      UV_CACHE_DIR: /__w/_uv_cache
    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libxrender-dev
          apt-get clean
          rm -rf /var/lib/apt/lists/*
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          python-version: '3.10'
          cache-local-path: /__w/_uv_cache
      - name: Install PyTorch
        run: |
          uv pip install torch==2.5.1 torchvision
      - name: Check disk space
        continue-on-error: true
        run: |
          df -h
          rm -rf /__t/go
          rm -rf /__t/node
          rm -rf /__t/Ruby
          rm -rf /__t/CodeQL
          cat /proc/cpuinfo  | grep -ic proc
          free
          df -h
      - name: Install unit tests dependencies
        run: |
          uv pip install onedl-mim
          mim install onedl-mmcv --only-binary=onedl-mmcv
          uv export --only-group codebases > codebases.txt && mim install -r codebases.txt
          uv pip install -r pyproject.toml --group tests --group build --extra backends
      - name: Build and install
        run: |
          rm -rf .eggs && python -m pip install -e .
          python tools/check_env.py
      - name: Run unittests and generate coverage report
        id: badge_status
        run: |
          coverage run --branch --source mmdeploy -m pytest -rsE tests
          coverage xml
          coverage report -m
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          format: markdown
          output: both
          hide_branch_rate: false
