name: cross-arch-build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'csrc/**'
      - "CMakeLists.txt"
  push:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PIP_PRE: 1

jobs:
  # takes a long time, so only do it when csrc is changed
  cross_build_aarch64:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      PIP_PRE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: update
        run: sudo apt update
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: gcc-multilib
        id: badge_status
        run: |
          sh -ex tools/scripts/ubuntu_cross_build_aarch64.sh
      - name: create badge
        if: always()
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: cross_build_aarch64
          LABEL: 'build'
          STATUS: ${{ steps.badge_status.conclusion == 'success' && 'passing' || 'failing' }}
          COLOR: ${{ steps.badge_status.conclusion == 'success' && 'green' || 'red' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
